import { useState } from 'react'
import { generate } from '../generator/generate.js'
import { CATEGORIES, CATEGORY_KEYS } from '../generator/categories.js'

// Live showcase: visitor picks a business name + category, the generator runs
// IN-BROWSER (Free tier = HTML/CSS/JS), and the result renders in an iframe.
// Higher + Top tiers point to pre-rendered React builds (generated by generator/cli.mjs).
const DEMOS = [
  { label: 'Saffron Table · Higher', tier: 'higher', name: 'saffron-table', cat: 'restaurant' },
  { label: 'Saffron Table · Top', tier: 'top', name: 'saffron-table', cat: 'restaurant' },
  { label: 'Lumière Salon · Higher', tier: 'higher', name: 'lumi-re-salon', cat: 'salon' },
  { label: 'Lumière Salon · Top', tier: 'top', name: 'lumi-re-salon', cat: 'salon' },
]

function blobUrl(files) {
  const html = files['index.html']
  const css = files['styles.css'] || ''
  const js = files['script.js'] || ''
  const inlined = html
    .replace('<link rel="stylesheet" href="styles.css">', `<style>${css}</style>`)
    .replace('<script src="script.js"></script>', `<script>${js}</script>`)
  return URL.createObjectURL(new Blob([inlined], { type: 'text/html' }))
}

export default function GeneratorShowcase() {
  const [name, setName] = useState('Piano Bistro')
  const [category, setCategory] = useState('restaurant')
  const [tab, setTab] = useState('free') // free | higher | top
  const [url, setUrl] = useState(() => {
    const out = generate({ name: 'Piano Bistro', category: 'restaurant' }, { tier: 'free' })
    return blobUrl(out.files)
  })

  function regenerate() {
    const out = generate({ name, category }, { tier: 'free' })
    const u = blobUrl(out.files)
    setUrl((old) => {
      if (old) URL.revokeObjectURL(old)
      return u
    })
  }

  function loadDemo(d) {
    setTab(d.tier)
    if (d.tier !== 'free') {
      const src = `${import.meta.env.BASE_URL}demos/${d.tier}-${d.name}/build/index.html`
      setUrl((old) => {
        if (old && old.startsWith('blob:')) URL.revokeObjectURL(old)
        return src
      })
    } else {
      regenerate()
    }
  }

  return (
    <section id="generator" className="generator">
      <div className="container section-head">
        <h2>See the generator build a site</h2>
        <p>Pick a business. The generator picks the layout and stack. Free tier renders live in your browser.</p>
      </div>

      <div className="container gen-controls">
        <input
          aria-label="Business name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Business name"
        />
        <select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Category">
          {CATEGORY_KEYS.map((k) => (
            <option key={k} value={k}>
              {CATEGORIES[k].label}
            </option>
          ))}
        </select>
        <button className="btn btn-primary" onClick={regenerate}>
          Generate
        </button>
      </div>

      <div className="container gen-tabs">
        <button className={tab === 'free' ? 'active' : ''} onClick={() => loadDemo({ tier: 'free', name, cat: category })}>
          Free — HTML/CSS/JS
        </button>
        {DEMOS.map((d) => (
          <button key={d.label} className={tab === d.tier ? 'active' : ''} onClick={() => loadDemo(d)}>
            {d.label}
          </button>
        ))}
      </div>

      <div className="container">
        <iframe
          className="gen-frame"
          title="Generated site preview"
          src={url}
          sandbox="allow-scripts allow-same-origin"
        />
      </div>
    </section>
  )
}
